#!/bin/bash
echo 			Kalkulator
echo 		1.Dodawanie
echo		2.Odejmowanie
echo		3.Mnozenie
echo		4.Dzielenie
read -r dzialanie

echo Pierwsza liczba
read -r a
echo Druga liczba
read -r b

case $dzialanie in 
1)echo Dodawanie
res=$((a+b))
;;
2) echo Odejmowanie
res=$((a-b))
;;
3) echo Mnozenie
res=$((a*b))
;;
4) echo Dzielenie
res=$((a/b))
esac
echo "Result : $res"
